name: tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: install requirements
        run: pip install -r requirements.dev

      - name: tests
        run: pytest
